//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchasing
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSummary
    {
        public string Customer { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> Items { get; set; }
    }
}
